<?php
/* 
    generated by Symfony (php bin/console make:entity) 
    @author ali-kemal.yalama ( ali-kemal.yalama@iubh.de ) 

    Last edit by karim.saad (karim.saad@iubh.de) 01.02.22 0102
*/

namespace App\Repository;

use App\Entity\Modul;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @method Modul|null find($id, $lockMode = null, $lockVersion = null)
 * @method Modul|null findOneBy(array $criteria, array $orderBy = null)
 * @method Modul[]    findAll()
 * @method Modul[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class ModulRepository extends ServiceEntityRepository
{
    public function __construct ( ManagerRegistry $registry )
    {
        parent::__construct ( $registry, Modul::class );
    }

    public function getAllModules () 
    {
        $result = $this -> findAll ();

        return count ( $result );
    }
}
