<?php
/*
    generated by Symfony (php bin/console make:entity) run by ali-kemal.yalama ( ali-kemal.yalama@iubh.de ) 

    Last edit by karim.saad (karim.saad@iubh.de) 01.02.22 0102
*/

namespace App\Repository;

use App\Entity\Skript;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @method Skript|null find($id, $lockMode = null, $lockVersion = null)
 * @method Skript|null findOneBy(array $criteria, array $orderBy = null)
 * @method Skript[]    findAll()
 * @method Skript[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class SkriptRepository extends ServiceEntityRepository
{
    public function __construct ( ManagerRegistry $registry )
    {
        parent::__construct ( $registry, Skript::class );
    }
}
