<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

/**
 *  SecurityController manages all Security Routes 
 * 
 *  generated by php bin/console make:auth
 *  compare https://symfony.com/doc/current/security.html#the-user
 * 
 *  @author karim.saad ( karim.saad@iubh.de )
 *  code formatting fix 30.01.02.2022-01.02.2022 2300-0100 (karim.saad@iubh.de)
 */
class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     */
    public function login ( AuthenticationUtils $authenticationUtils ): Response
    {
        if ( $this -> getUser () )
            return $this -> redirectToRoute ( 'admin' );

        $error          = $authenticationUtils -> getLastAuthenticationError ();
        $lastUsername   = $authenticationUtils -> getLastUsername            ();

        return $this -> render ( 
            'security/login.html.twig',
            [
                'last_username' => $lastUsername,
                'error'         => $error
            ]
        );
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout ()
    {
        throw new \LogicException ( 'This method can be blank - it will be intercepted by the logout key on your firewall.' );
    }
}
